//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEntity.Concrete.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SID { get; set; }
        public decimal FeesDetail { get; set; }
        public string Name { get; set; }
        public string EducationDetail { get; set; }
        public string PersonelDetail { get; set; }
        public int CID { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
